-- VibeFlow Kanban Board Database Initialization Script
-- Oracle SQL Developer
-- Created based on project-scope-database.md and database-schema.md

-- Drop tables if they exist (for clean setup)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE WORK_LOGS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ASSIGNMENT_HISTORY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROJECT_MEMBERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PROJECTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TASKS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create USERS table
CREATE TABLE USERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    name VARCHAR2(255),
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PROJECTS table
CREATE TABLE PROJECTS (
    id           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(255) NOT NULL,
    key          VARCHAR2(10)  NOT NULL,
    description  VARCHAR2(1000),
    owner_id     NUMBER,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_project_key UNIQUE (key),
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES USERS(id)
);

-- Create PROJECT_MEMBERS table
CREATE TABLE PROJECT_MEMBERS (
    project_id  NUMBER NOT NULL,
    user_id     NUMBER NOT NULL,
    role        VARCHAR2(50) DEFAULT 'member',
    joined_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_project_members PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE,
    CONSTRAINT fk_pm_user    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- Create TASKS table
CREATE TABLE TASKS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000) NULL,
    status VARCHAR2(50) DEFAULT 'Backlog' CHECK (status IN (
        'Backlog', 'Todo', 'In Progress', 'Review',
        'Testing', 'Done', 'Blocked', 'Archived'
    )),
    assignee_id NUMBER NULL,
    due_date TIMESTAMP NULL,
    created_by NUMBER NOT NULL,
    position NUMBER DEFAULT 0,
    project_id NUMBER NULL,
    issue_type VARCHAR2(20) DEFAULT 'Task',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id)
        REFERENCES USERS(id) ON DELETE SET NULL,
    CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by)
        REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_project FOREIGN KEY (project_id)
        REFERENCES PROJECTS(id) ON DELETE CASCADE
);

-- Create ASSIGNMENT_HISTORY table
CREATE TABLE ASSIGNMENT_HISTORY (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL,
    old_assignee_id NUMBER NULL,
    new_assignee_id NUMBER NULL,
    changed_by NUMBER NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_assignment_task FOREIGN KEY (task_id) 
        REFERENCES TASKS(id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_old_assignee FOREIGN KEY (old_assignee_id) 
        REFERENCES USERS(id) ON DELETE SET NULL,
    CONSTRAINT fk_assignment_new_assignee FOREIGN KEY (new_assignee_id) 
        REFERENCES USERS(id) ON DELETE SET NULL,
    CONSTRAINT fk_assignment_changed_by FOREIGN KEY (changed_by) 
        REFERENCES USERS(id) ON DELETE CASCADE
);

-- Create WORK_LOGS table
CREATE TABLE WORK_LOGS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    hours_logged NUMBER(5,2) NOT NULL CHECK (hours_logged > 0),
    description VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_worklogs_task FOREIGN KEY (task_id) 
        REFERENCES TASKS(id) ON DELETE CASCADE,
    CONSTRAINT fk_worklogs_user FOREIGN KEY (user_id) 
        REFERENCES USERS(id) ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX idx_tasks_status ON TASKS(status);
CREATE INDEX idx_tasks_position ON TASKS(position);
CREATE INDEX idx_worklogs_task_id ON WORK_LOGS(task_id);
CREATE INDEX idx_assignment_history_task_id ON ASSIGNMENT_HISTORY(task_id);
CREATE INDEX idx_tasks_assignee_id ON TASKS(assignee_id);
CREATE INDEX idx_tasks_created_by ON TASKS(created_by);
CREATE INDEX idx_tasks_project_id ON TASKS(project_id);

-- Create view for reporting (KPI 30-34)
CREATE OR REPLACE VIEW TASK_REPORT_VIEW AS
SELECT 
    t.id,
    t.title,
    t.status,
    u.email as assignee_email,
    creator.email as created_by_email,
    COALESCE(SUM(wl.hours_logged), 0) as total_hours
FROM TASKS t
LEFT JOIN USERS u ON t.assignee_id = u.id
LEFT JOIN USERS creator ON t.created_by = creator.id
LEFT JOIN WORK_LOGS wl ON t.id = wl.task_id
GROUP BY t.id, t.title, t.status, u.email, creator.email;

-- Insert sample data for testing
-- Sample users (passwords are hashed with bcrypt: 'password123')
INSERT INTO USERS (email, name, password_hash) VALUES ('admin@vibeflow.com', 'Admin User', '$2b$10$ExampleHashForPassword123');
INSERT INTO USERS (email, name, password_hash) VALUES ('user1@vibeflow.com', 'User One', '$2b$10$ExampleHashForPassword123');
INSERT INTO USERS (email, name, password_hash) VALUES ('user2@vibeflow.com', 'User Two', '$2b$10$ExampleHashForPassword123');

-- Sample project
INSERT INTO PROJECTS (name, key, description, owner_id) VALUES ('VibeFlow Development', 'VF', 'Main development project', 1);

-- Sample tasks
INSERT INTO TASKS (title, status, assignee_id, created_by, position, project_id, issue_type) 
VALUES ('Implement authentication', 'Backlog', 1, 1, 1, 1, 'Task');

INSERT INTO TASKS (title, status, assignee_id, created_by, position, project_id, issue_type) 
VALUES ('Design database schema', 'Todo', 2, 1, 2, 1, 'Task');

INSERT INTO TASKS (title, status, assignee_id, created_by, position, project_id, issue_type) 
VALUES ('Build Kanban UI', 'In Progress', 1, 2, 1, 1, 'Task');

-- Sample assignment history
INSERT INTO ASSIGNMENT_HISTORY (task_id, old_assignee_id, new_assignee_id, changed_by)
VALUES (1, NULL, 1, 1);

INSERT INTO ASSIGNMENT_HISTORY (task_id, old_assignee_id, new_assignee_id, changed_by)
VALUES (2, NULL, 2, 1);

-- Sample work logs
INSERT INTO WORK_LOGS (task_id, user_id, hours_logged, description)
VALUES (1, 1, 2.5, 'Initial research and planning');

INSERT INTO WORK_LOGS (task_id, user_id, hours_logged, description)
VALUES (1, 1, 1.0, 'Implementation of login endpoint');

INSERT INTO WORK_LOGS (task_id, user_id, hours_logged, description)
VALUES (3, 2, 4.0, 'UI component development');

COMMIT;

-- Verification queries
SELECT 'Database initialized successfully' as message FROM DUAL;
SELECT COUNT(*) as user_count FROM USERS;
SELECT COUNT(*) as project_count FROM PROJECTS;
SELECT COUNT(*) as task_count FROM TASKS;
SELECT COUNT(*) as worklog_count FROM WORK_LOGS;