const { executeQuery, executeQuerySingle, executeQueryRows } = require('../config/database');
const oracledb = require('oracledb');

/**
 * Try to run a DDL safely (ignore if already exists or column exists)
 */
async function tryAlter(sql) {
  try {
    await executeQuery(sql);
    console.log(`✅ Migration: ${sql.substring(0, 60)}...`);
  } catch (err) {
    // ORA-01430: column already exists; ORA-00955: object name already used
    if (err.message && (err.message.includes('ORA-01430') || err.message.includes('ORA-00955') || err.message.includes('ORA-02275') || err.message.includes('ORA-00942'))) {
      console.log(`⚠️  Already exists, skipping: ${sql.substring(0, 60)}...`);
    } else {
      console.error(`❌ Migration failed: ${err.message}`);
    }
  }
}

async function runMigrations() {
  console.log('Running project layer migrations...');

  // Create PROJECTS table
  await tryAlter(`
    CREATE TABLE PROJECTS (
      id           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      name         VARCHAR2(255) NOT NULL,
      key          VARCHAR2(10)  NOT NULL,
      description  VARCHAR2(1000),
      owner_id     NUMBER,
      created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_project_key UNIQUE (key),
      CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES USERS(id)
    )
  `);

  // Create PROJECT_MEMBERS table
  await tryAlter(`
    CREATE TABLE PROJECT_MEMBERS (
      project_id  NUMBER NOT NULL,
      user_id     NUMBER NOT NULL,
      role        VARCHAR2(50) DEFAULT 'member',
      joined_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT pk_project_members PRIMARY KEY (project_id, user_id),
      CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE,
      CONSTRAINT fk_pm_user    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
    )
  `);

  // Add project_id to TASKS
  await tryAlter(`ALTER TABLE TASKS ADD project_id NUMBER`);

  // Add issue_type to TASKS
  await tryAlter(`ALTER TABLE TASKS ADD issue_type VARCHAR2(20) DEFAULT 'Task'`);

  // Add FK for project_id
  await tryAlter(`
    ALTER TABLE TASKS ADD CONSTRAINT fk_task_project
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE
  `);

  // Add parent_id to TASKS for sub-tasks
  await tryAlter(`ALTER TABLE TASKS ADD parent_id NUMBER`);
  await tryAlter(`
    ALTER TABLE TASKS ADD CONSTRAINT fk_task_parent
    FOREIGN KEY (parent_id) REFERENCES TASKS(id) ON DELETE CASCADE
  `);

  // Create COMMENTS table
  await tryAlter(`
    CREATE TABLE COMMENTS (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_id NUMBER NOT NULL,
      user_id NUMBER NOT NULL,
      content VARCHAR2(4000) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_comment_task FOREIGN KEY (task_id) REFERENCES TASKS(id) ON DELETE CASCADE,
      CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
    )
  `);

  // Create ACTIVITY_LOGS table
  await tryAlter(`
    CREATE TABLE ACTIVITY_LOGS (
      id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      task_id NUMBER NOT NULL,
      user_id NUMBER NOT NULL,
      action VARCHAR2(100) NOT NULL,
      old_value VARCHAR2(1000),
      new_value VARCHAR2(1000),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT fk_activity_task FOREIGN KEY (task_id) REFERENCES TASKS(id) ON DELETE CASCADE,
      CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
    )
  `);

  // Create / refresh the reporting view (idempotent)
  await tryAlter(`
    CREATE OR REPLACE VIEW TASK_REPORT_VIEW AS
    SELECT
      t.id,
      t.title,
      t.status,
      t.project_id,
      u.email  AS assignee_email,
      u.name   AS assignee_name,
      creator.email AS created_by_email,
      COALESCE(SUM(wl.hours_logged), 0) AS total_hours
    FROM TASKS t
    LEFT JOIN USERS u       ON t.assignee_id = u.id
    LEFT JOIN USERS creator ON t.created_by  = creator.id
    LEFT JOIN WORK_LOGS wl  ON t.id          = wl.task_id
    GROUP BY t.id, t.title, t.status, t.project_id, u.email, u.name, creator.email
  `);

  // Data migration: Ensure users with orphan tasks have a project to view them in
  try {
    const orphanUsers = await executeQueryRows(`
      SELECT DISTINCT created_by FROM TASKS WHERE project_id IS NULL
    `);
    
    for (const u of orphanUsers) {
      const userId = u.CREATED_BY || u.created_by;
      if (!userId) continue;

      console.log(`🌱 Seeding default project for user ${userId}...`);
      
      // Create a default project for this user
      const result = await executeQuery(
        'INSERT INTO PROJECTS (name, key, description, owner_id) VALUES (:name, :key, :description, :ownerId) RETURNING id INTO :id',
        { 
          name: 'My First Project', 
          key: `PROJ${userId}`.substring(0, 10), 
          description: 'Auto-generated project for your existing tasks', 
          ownerId: userId, 
          id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER } 
        }
      );
      const projectId = result.outBinds.id[0];
      
      // Add as admin
      await executeQuery(
        'INSERT INTO PROJECT_MEMBERS (project_id, user_id, role) VALUES (:projectId, :userId, :role)',
        { projectId, userId, role: 'admin' }
      );
      
      // Link tasks
      const updateResult = await executeQuery(
        'UPDATE TASKS SET project_id = :projectId WHERE project_id IS NULL AND created_by = :userId',
        { projectId, userId }
      );
      console.log(`✅ Created project ${projectId} and linked ${updateResult.rowsAffected || 0} tasks for user ${userId}`);
    }
    
    // Also ensure the demo user (ID 1) has the "VibeFlow Development" project if missing
    const demoProject = await executeQuerySingle("SELECT id FROM PROJECTS WHERE key = 'VF'");
    if (!demoProject) {
        // ... create VF project ...
    }

    // Ensure every user has at least one project
    const allUsers = await executeQueryRows('SELECT id FROM USERS');
    for (const user of allUsers) {
        const userId = user.ID || user.id;
        const userProjects = await executeQuerySingle('SELECT COUNT(*) as cnt FROM PROJECT_MEMBERS WHERE user_id = :userId', { userId });
        if ((userProjects?.CNT || userProjects?.cnt || 0) === 0) {
            console.log(`🌱 Creating initial project for user ${userId}...`);
            const res = await executeQuery(
                'INSERT INTO PROJECTS (name, key, description, owner_id) VALUES (:name, :key, :description, :ownerId) RETURNING id INTO :id',
                { 
                    name: 'My Workspace', 
                    key: `WS${userId}`.substring(0, 10), 
                    description: 'Initial workspace for your tasks', 
                    ownerId: userId, 
                    id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER } 
                }
            );
            const projectId = res.outBinds.id[0];
            await executeQuery(
                'INSERT INTO PROJECT_MEMBERS (project_id, user_id, role) VALUES (:projectId, :userId, :role)',
                { projectId, userId, role: 'admin' }
            );
            
            // Link any orphan tasks they might have (fallback)
            await executeQuery(
                'UPDATE TASKS SET project_id = :projectId WHERE project_id IS NULL AND created_by = :userId',
                { projectId, userId }
            );
        }
    }
  } catch (err) {
    console.error('⚠️ Data migration warning:', err.message);
  }

  console.log('✅ All project layer migrations complete');
}

module.exports = { runMigrations };
